// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:468272272410:web:eacfe950c740abb8cfada3',
    messagingSenderId: '468272272410',
    projectId: 'eventure-b3ff2',
    authDomain: 'eventure-b3ff2.firebaseapp.com',
    storageBucket: 'eventure-b3ff2.firebasestorage.app',
    measurementId: 'G-F6TCWM82VP',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:468272272410:android:480cd888641704f5cfada3',
    messagingSenderId: '468272272410',
    projectId: 'eventure-b3ff2',
    storageBucket: 'eventure-b3ff2.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:468272272410:ios:ee650aa2879ed088cfada3',
    messagingSenderId: '468272272410',
    projectId: 'eventure-b3ff2',
    storageBucket: 'eventure-b3ff2.firebasestorage.app',
    iosBundleId: 'com.example.eventure',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY']!,
    appId: '1:468272272410:ios:ed7e09c9dc73c48fcfada3',
    messagingSenderId: '468272272410',
    projectId: 'eventure-b3ff2',
    storageBucket: 'eventure-b3ff2.firebasestorage.app',
    iosBundleId: 'com.example.eventure.RunnerTests',
  );
}
